language: R
sudo: required
cache: packages
warnings_are_errors: true

before_install:
  - sudo apt-get install -y libudunits2-dev

r:
  - release
  - devel

r_packages:
  - devtools
  - covr

after_success:
- Rscript -e 'covr::codecov()'
