language: R
sudo: required
cache: packages
warnings_are_errors: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libunits-bin
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - libgdal-dev
      - libjson-c-dev
      - libnetcdf-dev
      - netcdf-bin
      
r:
  - release
  - devel

r_packages:
  - devtools
  - covr
  - rgdal

after_success:
  - Rscript -e 'covr::codecov()'
